export const GET_POPULAR_MOVIES = 'GET_POPULAR_MOVIES';
export const UPDATE_FAVOURITE_MOVIES = 'UPDATE_FAVOURITE_MOVIES';
export const GET_FAVOURITE_MOVIES = 'GET_FAVOURITE_MOVIES';
export const AUTH_USER = 'AUTH_USER';
