export const GET_POPULAR_MOVIES = 'GET_POPULAR_MOVIES';
export const UPDATE_FAVOURITE_MOVIES = 'UPDATE_FAVOURITE_MOVIES';
export const GET_FAVOURITE_MOVIES = 'GET_FAVOURITE_MOVIES';

export const GET_POPULAR_MOVIES_GUEST = 'GET_POPULAR_MOVIES_GUEST';
export const UPDATE_FAVOURITE_MOVIES_GUEST = 'UPDATE_FAVOURITE_MOVIES_GUEST';
export const GET_FAVOURITE_MOVIES_GUEST = 'GET_FAVOURITE_MOVIES_GUEST';

export const AUTH_USER = 'AUTH_USER';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_LOADING = 'USER_LOGIN_LOADING';
export const USER_LOGIN_SUCCES = 'USER_LOGIN_SUCCES';
export const USER_LOGIN_ERR = 'USER_LOGIN_ERR';

export const USER_SESSION = 'USER_SESSION';
export const SESSION_LOGOUT = 'SESSION_LOGOUT';
export const SET_USER_STATE = 'SET_USER_STATE';
export const RESET_USER_STATE = 'RESET_USER_STATE';

export const USER_REGISTRATION = 'USER_REGISTRATION';

export const STORE_FAVORITE_MOVIES = 'STORE_FAVORITE_MOVIES';
